Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\py2exe\boot_common.py", line 92, in <module>
    import linecache
  File "linecache.pyc", line 9, in <module>
  File "os.pyc", line 63, in <module>
  File "ntpath.pyc", line 15, in <module>
ImportError: cannot import name _unicode
Traceback (most recent call last):
  File "Base_s.py", line 5, in <module>
    import os
  File "os.pyc", line 63, in <module>
  File "ntpath.pyc", line 15, in <module>
ImportError: cannot import name _unicode
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\py2exe\boot_common.py", line 92, in <module>
    import linecache
  File "linecache.pyc", line 9, in <module>
  File "os.pyc", line 63, in <module>
  File "ntpath.pyc", line 15, in <module>
ImportError: cannot import name _unicode
Traceback (most recent call last):
  File "Base_s.py", line 5, in <module>
    import os
  File "os.pyc", line 63, in <module>
  File "ntpath.pyc", line 15, in <module>
ImportError: cannot import name _unicode
